### ISSUE TITLE
BACTpipe workflow completed without errors 

### ISSUE THREAD

**Issue by thorellk** [ctmrbio/BACTpipe#142]
"BACTpipe workflow completed without errors " is the output regardless as far as I can see. Even when I ran it last night and basically every process failed due to write errors (not BACTpipe related). What are the criteria for this message?

**Comment by abhi18av** [comment]
Hi @thorellk - good catch!

I can't believe that even after watching it fail (during dev) so many times, I didn't catch this peculiarity.

The issue was in the design of `workflow.onComplete` block, I've updated that logic using the details from 
https://www.nextflow.io/docs/latest/metadata.html#decoupling-metadata


I've added the linked quick PR for this. Please let me know if that worked or not.
